# Generated by Django 5.2.4 on 2025-08-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('anomaly_count', models.IntegerField(blank=True, null=True)),
                ('bias_score', models.FloatField(blank=True, null=True)),
                ('dataset_size', models.CharField(blank=True, max_length=100)),
                ('dataset_cid', models.CharField(blank=True, max_length=100)),
                ('analysis_cid', models.CharField(blank=True, max_length=100)),
                ('verification_url', models.URLField(blank=True)),
                ('key_insights', models.JSONField(blank=True, default=dict)),
                ('visualization_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
