# Generated by Django 5.2.4 on 2025-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0002_alter_datasetanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetanalysis',
            name='anomaly_examples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='critical_anomalies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='missing_values_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='moderate_anomalies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='processing_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='validity_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='validity_score',
            field=models.FloatField(null=True),
        ),
    ]
