# Generated by Django 5.2.4 on 2025-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0003_datasetanalysis_anomaly_examples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetanalysis',
            name='anomaly_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='bias_score',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='dataset_size',
            field=models.CharField(blank=True, default=100, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='quality_score',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
