# Generated by Django 5.2.4 on 2025-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0004_alter_datasetanalysis_anomaly_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetanalysis',
            name='columns_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='full_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datasetanalysis',
            name='rows_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
    ]
