# Generated by Django 5.2.4 on 2025-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ai', '0005_datasetanalysis_columns_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetanalysis',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='bias_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='dataset_size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetanalysis',
            name='validity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
